import { Page, expect } from '@playwright/test';

/*
 * Helper functions for computing a report “signature” and waiting for the
 * report to reach a settled state. A signature is generated by reading
 * the inner text of critical DOM nodes. Stability is achieved when the
 * signature remains constant across consecutive polls within a given
 * timeout window.
 */

// Critical selectors to consider when constructing the signature.
// Some axis IDs (IR and T2D) are aliased to Sugar and t2dVal respectively
// because those names were observed in the current HTML.
const SIGNATURE_SELECTORS: string[] = [
  '#heroPhenotype',
  '#heroOverall',
  '#heroMetAge',
  '#axisIRVal',
  '#axisSugarVal',
  '#axisMASLDVal',
  '#axisT2DVal',
  '#t2dVal',
  '#axisCVDVal',
  '#axisLGCIVal',
  '#cvdH5y',
  '#cvdH10y',
  '#cvdH20y',
];

/**
 * Capture a string signature representing the current visible values of the
 * report’s critical nodes. Missing elements are skipped.
 */
export async function captureSignature(page: Page): Promise<string> {
  const parts: string[] = [];
  for (const id of SIGNATURE_SELECTORS) {
    const element = await page.$(id);
    if (element) {
      const text = (await element.innerText()).trim();
      parts.push(`${id}:${text}`);
    }
  }
  return parts.join('|');
}

/**
 * Poll the report signature until it remains unchanged between intervals.
 * Throws an error if stability is not reached within the timeout.
 */
export async function waitForStableReport(
  page: Page,
  timeout: number = 10000,
  interval: number = 500
): Promise<void> {
  let lastSig = '';
  const start = Date.now();
  while (Date.now() - start < timeout) {
    const sig = await captureSignature(page);
    if (sig && sig === lastSig) {
      return;
    }
    lastSig = sig;
    await page.waitForTimeout(interval);
  }
  throw new Error('Report signature did not stabilize within the allotted time');
}

/**
 * Verify that all critical nodes and cards exist on the report page. This
 * function asserts that each selector resolves to at least one element in the DOM.
 */
export async function verifyCriticalNodes(page: Page): Promise<void> {
  const selectors = [
    '#heroPhenotype',
    '#heroOverall',
    '#heroMetAge',
    '#axisMASLDVal',
    '#axisCVDVal',
    '#axisLGCIVal',
    '#cvdH5y',
    '#cvdH10y',
    '#cvdH20y',
    '#card-mets',
    '#lgciCard',
  ];
  for (const selector of selectors) {
    const locator = page.locator(selector);
    await expect(locator, `Expected ${selector} to exist`).toHaveCount(1);
  }
}